### ISSUE TITLE
ReceiveAndKeep value in enum ReceiveType is just a peek operation

### ISSUE THREAD

**Issue by Splaxi** [tommagumma/PSServiceBus#1]
I was first very confused with the name "ReceiveAndKeep" because nothing like that exists when we are talking about service bus queues. I took a chance and tried to use the default value at first, against a test service bus queue and it worked flawlessly.

The more I play with it, I believe everyone would benefit from using the correct names / verbs for the action that you are trying to expose in module. It makes it easier for people to read about different concepts and follow along other guides, even though they are using this module.

As a mitigation, I suggest that we simply have 2 enums, that does the same. We are keeping the original "ReceiveAndKeep", so we don't introduce any breaking changes. And we add the "PeekOnly" option as well, for people that know about the concepts and knows what they are after.

**Comment by tmeadon** [comment]
Hey @Splaxi - thanks for your contribution!  I totally agree with this.  Let me fix the problem with the build and I will review the PR.

**Comment by tmeadon** [comment]
PR merged.
