### ISSUE TITLE
Build step is being skipped when PR validation runs

### ISSUE THREAD

**Issue by tmeadon** [tommagumma/PSServiceBus#11]
As in this build pipeline run, the build step is being skipped when it is triggered by a pull request - https://dev.azure.com/tommagumma1/PSServiceBus/_build/results?buildId=34&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9.

This is due to the pipeline secrets not being available to PRs from forks (see https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#validate-contributions-from-forks).  I need to investigate how to get the PR validation working properly whilst not running the risk of exposing any secrets.

**Comment by Splaxi** [comment]
Not sure how you did design your pipeline. But if you store the secret in the pipeline variables and mark it as a secret, Azure DevOps should mask it in the console output.

Clone the pipeline, edit it and run it by hand. See the results and delete it. You could configure the secret to a fake value and test that you can't locate it, before trying it for real. 

Just an idea!

**Comment by tmeadon** [comment]
That's how I've got it set up now.  I think the issue is that there's potential for someone to fork the repo, change the build pipeline to do something bad with the secret then create a PR.  Not sure, needs a bit of thought so I logged this to stop me from forgetting about it!

**Comment by tmeadon** [comment]
Resolved by https://github.com/tommagumma/PSServiceBus/commit/b5e49c407f3c77f8b81892cfe4cad7e17094dccd

**Comment by Splaxi** [comment]
Nice catch!
