### ISSUE TITLE
Implement supporting features for Send-SbMessagesInBatch

### ISSUE THREAD

**Issue by Splaxi** [tommagumma/PSServiceBus#13]
There is a hard limit on how many messages you can send to the Queue / Topic.

It is based on your SKU ( Free/Standard = 256K & Premium = 1 MB). So the sum of size per message, has to be under the limits of the maximum size a message can be, based on your tier/sku.

I suggest that we add capabilities to report max batch size on the Queue. Where do we find the Tier / SKU the Service Bus Namespace is deployed with?

We should consider adding a Test-SbMessageBatchSize, against the namespace tier/sku and throw an error if the total payload is beyond the size limit.

I believe that 100 messages is also a hard limit, which we should also test for when trying to send and fail hard on it.

**Comment by tmeadon** [comment]
Okay so that first question should be fairly simple - we can get the sku by using the `GetNamespaceInfoAsync()` method of the `ManagementClient` class we are using in `PSServiceBus.Helpers.SbManager`.  Something like this would do it:

```
public MessagingSku GetNamespaceSku()
{
    return this.managementClient.GetNamespaceInfoAsync().Result.MessagingSku;
}
```

I think reporting that max size is definitely a good idea, I will take a look at adding that today.  How would we match up the sku to the batch size?  Would we just store it statically in the code?

**Comment by tmeadon** [comment]
Also, I'm in no rush to get 1.1.0 out - shall we hold off publishing it until we have this sorted?

**Comment by Splaxi** [comment]
Publish what we have, so we can spend some time time on making this right 🤘

**Comment by Splaxi** [comment]
But yes, I would just keep base size for each sku in the code and use it to do the calculations.

**Comment by tmeadon** [comment]
Check out PR #15 - that should help.  I think the next thing I'll do is write the 'Test-SbMessageBatchSize' cmdlet that you mentioned - it will be useful for the user to be able to test that their messages are under the limit as well as for us to hard stop any send attempts that are over the limit.

**Comment by tmeadon** [comment]
I believe this can be closed now...

**Comment by Splaxi** [comment]
Looking forward to see the next release 🤘 Awesome work!
