### ISSUE TITLE
Implement 'Test-SbMessageBatchSize'

### ISSUE THREAD

**Issue by tmeadon** [tommagumma/PSServiceBus#16]
@Splaxi had the idea for this cmdlet in #13.  The purpose is to verify whether a given message or batch of messages will not exceed the message size limit for the in-scope namespace.

**Comment by Splaxi** [comment]
There are several things to consider here.

I would argue that a complete overview, that displays true/false for each tier/sku and less than 100 messages, would be very helpful. No need to parse a connection string or query the namespace for a generic response.

But if we pass or have a stored connection string in memory, it should an additional property ValidForNamespace true/false, based on the allowed MaxSize.

How does that sound?

**Comment by tmeadon** [comment]
Yeah, a richer output would definitely be useful.  How about something like this...?

```
PS> Test-SbMessageBatch -Messages $messages

BatchSize: xxx MB
NumberOfMessages: yy
ValidForBasicSku: {result: true/false; reason: too big / too many msgs}
ValidForStandardSku: {result: true/false; reason: too big / too many msgs}
ValidForPremiumSku: {result: true/false; reason: too big / too many msgs}
ValidForCurrentNamespace: {result: true/false; reason: too big / too many msgs}
```

Where did you find that 100 message-per-batch limit by the way?

**Comment by Splaxi** [comment]
I would think that the base output should be:

```
BatchSize: xxx MB
NumberOfMessages: yy
ValidForBasicSku: {result: true/false; reason: too big / too many msgs}
ValidForStandardSku: {result: true/false; reason: too big / too many msgs}
ValidForPremiumSku: {result: true/false; reason: too big / too many msgs}
```

And if the Namespace is in play, we should add the 
```
CurrentNamespaceSku: {Free, Standard, Premium}
ValidForCurrentNamespace: {result: true/false; reason: too big / too many msgs}
```

What ever reason we might find, should be posted as a warning message.

I'll dig around my search history, to see if I can find back to the reference of the 100 messages.

**Comment by tmeadon** [comment]
Cool, agreed on those points.  Let me know if you find details of that limit because I can't find documentation related to it - the only limit I've seen is on the total size of the batch.  If that's the case then we can probably do away with the reason property in that base output.

I'll proceed on the basis that there isn't a limit on the number of messages in a batch unless I hear from you!

**Comment by Splaxi** [comment]
That is a deal!

**Comment by Splaxi** [comment]
This is were I read about the 100.

https://github.com/MassTransit/MassTransit/issues/1409

![image](https://user-images.githubusercontent.com/8750181/74162669-6b891880-4c21-11ea-8eeb-b20e1b90c440.png)

**Comment by tmeadon** [comment]
Good find.  Let's add that constraint in then.

**Comment by Splaxi** [comment]
My testing shows that there ISN'T a hard limit on the number of messages allowed in a single batch. It is only size that counts.
