### ISSUE TITLE
Implement support for FetchQty and PrefetchQty in Purge 

### ISSUE THREAD

**Issue by Splaxi** [tommagumma/PSServiceBus#23]
Let's say that you have 100K messages, all below 1kb in size, that you want to purge from a queue.

There should be a significant difference between fetching 100 vs. 500. I think it should be fairly straightforward to get this into the module.

The same issue, but the other way around. Let's say you are maxing out the message size per single message. Then you would have to configure it to 1 for each property or the purge would fail.

I'll take the task on my shoulders 🖐️

**Comment by Splaxi** [comment]
If it works out like expected, we could make it part of the receive batch logic afterwards.

**Comment by tmeadon** [comment]
That all sounds reasonable to me, good luck!

**Comment by tmeadon** [comment]
Great work @Splaxi
