### ISSUE TITLE
Output Get-SbQueue -QueueName when done with Clear-SbQueue -QueueName

### ISSUE THREAD

**Issue by Splaxi** [tommagumma/PSServiceBus#27]
When working with purge, you want to make sure that all messages are deleted.

But if you have messages that are locked, they are not deleted, because they are still locked.

I think it would increase the user ability to simply output with Get-SbQueue -QueueName directly after the Clear-SbQueue is done.

How do you feel about that?

It could be either enabled / disabled with a parameter, if you want a clean execution.

**Comment by tmeadon** [comment]
That sounds good, it could be disabled as you say with a parameter called `-NoOutput`.  This should also cover subscriptions, which reminds me, should we add a `Clear-SbSubscription` cmdlet?  I know the functionality is covered in `Clear-SbQueue` but the naming of the cmdlet doesn't make that overly clear.

I wonder though how useful it would be if you weren't aware that the cause of the messages not being purged was because they're locked.  Should we also look to add the number of locked messages to the `SbQueue` and `SbSubscription` output types?

**Comment by Splaxi** [comment]
If you want to do anything around locked messages, then I would recommend that we implement a Test-SbQueueLockedMessages (or whatever name you believe is best) to do that.

Getting the queue details the way we do it today, is more natural. While a person learns more about service bus and what locktokens can do for you, there more specific will you be looking for that information.

But you could argue that we should display the "default lock" timeout setting for queues and subscriptions (which should be part of the runtimeinfo object)

I'm voting for the `-NoOutput` when using purge - brilliant idea!

**Comment by Splaxi** [comment]
We could argue that all of these should be part of the `Get-SbQueue`
![image](https://user-images.githubusercontent.com/8750181/74731760-fdf47200-5248-11ea-910d-9ec361619698.png)

**Comment by tmeadon** [comment]
Yeah you're right, it would probably be a fairly expensive process to find the number of locked messages seeing as it would need to peek every single message in the queue.  I guess if you wanted to do that you could just use the existing commands and filter - something like:

```
$messagesInQueue = Get-SbQueue -QueueName $queue | Select-Object -ExpandProperty ActiveMessages
$msgs = Receive-SbMessage -QueueName $queue -NumberOfMessagesToRetrieve $messagesInQueue -ReceiveType PeekOnly
$msgs.Where({$_.SystemProperties.IsLockTokenSet})
```

I think adding those additional queue properties would do absolutely no harm.  I think the current output is quite clean so would we also want to introduce a custom format to hide these properties by default?

**Comment by tmeadon** [comment]
Maybe `Clear-SbQueue` could also emit a warning if any locked messages are remaining after a purge?

**Comment by tmeadon** [comment]
I can take a look at this once #28 is done although if you fancy it feel free!

**Comment by Splaxi** [comment]
I'm going to focus on #23 and #25, so I'll leave this(#27) and #28 for you 😉
