### ISSUE TITLE
Implement more detail in the Get-SbQueue output

### ISSUE THREAD

**Issue by Splaxi** [tommagumma/PSServiceBus#28]
Based on the suggestion: https://github.com/tommagumma/PSServiceBus/issues/27#issuecomment-587413153 & https://github.com/tommagumma/PSServiceBus/issues/27#issuecomment-587416962

The task is up for grabs!

**Comment by tmeadon** [comment]
I got it! ✋

**Comment by Splaxi** [comment]
My test says this is a keeper!
