### ISSUE TITLE
Add "custom" output format

### ISSUE THREAD

**Issue by Splaxi** [tommagumma/PSServiceBus#5]
If the new properties PR #3 gets approved and merged into the module, I suggests that we add a custom format for the list view.

If you were to create the ps1xml file by hand, it should look like this:

```
<?xml version="1.0" encoding="utf-16"?>
<Configuration>
	<ViewDefinitions>
		<View>
			<Name>PSServiceBus.Outputs.SbMessage</Name>
			<ViewSelectedBy>
				<TypeName>PSServiceBus.Outputs.SbMessage</TypeName>
			</ViewSelectedBy>
			<ListControl>
				<ListEntries>
					<ListEntry>
						<ListItems>
							<ListItem>
								<PropertyName>MessageId</PropertyName>
							</ListItem>
							<ListItem>
								<PropertyName>UserProperties</PropertyName>
							</ListItem>
							<ListItem>
								<PropertyName>SystemProperties</PropertyName>
							</ListItem>
							<ListItem>
								<PropertyName>MessageBody</PropertyName>
							</ListItem>
						</ListItems>
					</ListEntry>
				</ListEntries>
			</ListControl>
		</View>
	</ViewDefinitions>
</Configuration>
```

But because everything in this module is code, I believe we need to look into the "FormatViewDefinition" class: 

https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.formatviewdefinition?view=powershellsdk-1.1.0

Getting examples on how to use it is actually pretty hard, but I've found that other repositories here on github actually use it. That is because it is public Microsoft repositories.

One simple example is here:
https://github.com/tibmeister/Powershell.Core.Utilities/blob/0e2526dad7312713d1a4d623b13b7b65065aeb36/Powershell.Core.Utilities/TestConnection.format.ps1xml.cs

I know that you rely on the InvokeBuild module and use that to build the solution. I don't know how to wrap things up, so that the build process can generate the PSServiceBus.ps1xml file needed.

I would expect it to be written to \output\xml\PSServiceBus.ps1xml and then update the PSServiceBus.psd1 file to contain:
```
FormatsToProcess = @('xml\PSServiceBus.Format.ps1xml')
```

Loading the module from here on should import the ps1xml file and that will enable a custom view for the format list.

**Comment by tmeadon** [comment]
Thanks for raising this, like the other issues you raised it looks like something we should implement.  I'll do a bit of research...

**Comment by tmeadon** [comment]
I think for the time being I'm happy to define custom formats statically and copy them into the output directory as part of the build process.  Hence #21!  If this becomes problematic we can revisit using something like the "FormatViewDefinitions" class as you suggested.

**Comment by tmeadon** [comment]
Custom format has been added!

**Comment by Splaxi** [comment]
I believe that you're missing the small details that you need to reference it, just like you do with the SbMessageBatchTestResult:

https://github.com/tommagumma/PSServiceBus/blob/87bfbe15ee265221c1a76ee0065a2953d10d2072/PSServiceBus.psd1#L65-L68

It should be done in `PSServiceBus.psd1`

**Comment by tmeadon** [comment]
Good catch, thanks!

https://github.com/tommagumma/PSServiceBus/pull/24

**Comment by Splaxi** [comment]
Team effort, that is what this is! 🤘

**Comment by tmeadon** [comment]
🤘 🤘
